<?php
/**
 * Created by PhpStorm.
 * User: jesign
 * Date: 7/19/19
 * Time: 9:06 PM
 */

namespace Tests\Http;


use App\Event;
use App\Participant;
use Tests\TestCase;

class ParticipantTest extends TestCase
{
    protected $event;
    protected $eventUrlPrefix;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->event = factory(Event::class)->create();
        $this->eventUrlPrefix = 'api/events/' . $this->event->id;
    }

    public function testParticipantIndex()
    {

        $response = $this->json('GET',$this->eventUrlPrefix . '/participants');
        $response->assertStatus(200);
    }

    public function testParticipantCreate()
    {
        $data = [
            'name' => 'John Doe'
        ];

        $response = $this->json('POST',$this->eventUrlPrefix . '/participants', $data);

        $response->assertStatus(200)->assertJson($data);
    }

    public function testParticipantUpdate()
    {
        $participant = factory(Participant::class)->create();
        $data = [
            'id' => $participant->id,
            'name' => 'Updated Name'
        ];

        $response = $this->json('POST',$this->eventUrlPrefix . '/participants', $data);

        $response->assertStatus(200)->assertJson($data);
    }

    public function testParticipantDelete() {
        $participant = factory(Participant::class)->create();

        $response = $this->json('POST',$this->eventUrlPrefix . '/participants/' . $participant->id . '/delete');

        $response->assertStatus(200)->assertJson([
            'success' => true
        ]);
    }
}